const pokedex = [
  { id: null, number: 1, name: 'Bulbasaur', type: 'grass', maxhp: 45, hp: 45, maxxp: 10, xp: 0, starter: true, canEvolve: true, evolvesFrom: null, rarity: 1, image: 'images/bulbasaur.png' },
  { id: null, number: 2, name: 'Ivysaur', type: 'grass', maxhp: 60, hp: 60, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Bulbasaur', rarity: 0, image: 'images/ivysaur.png' },
  { id: null, number: 3, name: 'Venusaur', type: 'grass', maxhp: 90, hp: 90, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Ivysaur', rarity: 0, image: 'images/venusaur.png' },
  { id: null, number: 4, name: 'Charmander', type: 'fire', maxhp: 45, hp: 45, maxxp: 10, xp: 0, starter: true, canEvolve: true, evolvesFrom: null, rarity: 1, image: 'images/charmander.png' },
  { id: null, number: 5, name: 'Charmeleon', type: 'fire', maxhp: 60, hp: 60, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Charmander', rarity: 0, image: 'images/charmeleon.png' },
  { id: null, number: 6, name: 'Charizard', type: 'fire', maxhp: 90, hp: 90, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Charmeleon', rarity: 0, image: 'images/charizard.png' },
  { id: null, number: 7, name: 'Squirtle', type: 'water', maxhp: 45, hp: 45, maxxp: 10, xp: 0, starter: true, canEvolve: true, evolvesFrom: null, rarity: 1, image: 'images/squirtle.png' },
  { id: null, number: 8, name: 'Wartortle', type: 'water', maxhp: 60, hp: 60, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Squirtle', rarity: 0, image: 'images/wartortle.png' },
  { id: null, number: 9, name: 'Blastoise', type: 'water', maxhp: 90, hp: 90, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Wartortle', rarity: 0, image: 'images/blastoise.png' },
  { id: null, number: 10, name: 'Caterpie', type: 'bug', maxhp: 25, hp: 25, maxxp: 5, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 10, image: 'images/caterpie.png' },
  { id: null, number: 11, name: 'Metapod', type: 'bug', maxhp: 50, hp: 50, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Caterpie', rarity: 0, image: 'images/metapod.png' },
  { id: null, number: 12, name: 'Butterfree', type: 'bug', maxhp: 70, hp: 70, maxxp: 15, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Metapod', rarity: 0, image: 'images/butterfree.png' },
  { id: null, number: 13, name: 'Weedle', type: 'bug', maxhp: 25, hp: 25, maxxp: 5, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 10, image: 'images/weedle.png' },
  { id: null, number: 14, name: 'Kakuna', type: 'bug', maxhp: 45, hp: 45, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Weedle', rarity: 0, image: 'images/kakuna.png' },
  { id: null, number: 15, name: 'Beedrill', type: 'bug', maxhp: 75, hp: 75, maxxp: 15, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Kakuna', rarity: 0, image: 'images/beedrill.png' },
  { id: null, number: 16, name: 'Pidgey', type: 'normal', maxhp: 30, hp: 30, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 10, image: 'images/pidgey.png' },
  { id: null, number: 17, name: 'Pidgeotto', type: 'normal', maxhp: 55, hp: 55, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Pidgey', rarity: 0, image: 'images/pidgeotto.png' },
  { id: null, number: 18, name: 'Pidgeot', type: 'normal', maxhp: 70, hp: 70, maxxp: 20, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Pidgeotto', rarity: 0, image: 'images/pidgeot.png' },
  { id: null, number: 19, name: 'Rattata', type: 'normal', maxhp: 30, hp: 30, maxxp: 5, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 10, image: 'images/rattata.png' },
  { id: null, number: 20, name: 'Raticate', type: 'normal', maxhp: 55, hp: 55, maxxp: 15, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Rattata', rarity: 0, image: 'images/raticate.png' },
  { id: null, number: 21, name: 'Spearow', type: 'normal', maxhp: 35, hp: 35, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 10, image: 'images/spearow.png' },
  { id: null, number: 22, name: 'Fearow', type: 'normal', maxhp: 65, hp: 65, maxxp: 15, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Spearow', rarity: 0, image: 'images/fearow.png' },
  { id: null, number: 23, name: 'Ekans', type: 'poison', maxhp: 35, hp: 35, maxxp: 5, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 9, image: 'images/ekans.png' },
  { id: null, number: 24, name: 'Arbok', type: 'poison', maxhp: 60, hp: 60, maxxp: 15, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Ekans', rarity: 0, image: 'images/arbok.png' },
  { id: null, number: 25, name: 'Pikachu', type: 'electric', maxhp: 45, hp: 45, maxxp: 10, xp: 0, starter: true, canEvolve: true, evolvesFrom: null, rarity: 1, image: 'images/pikachu.png' },
  { id: null, number: 26, name: 'Raichu', type: 'electric', maxhp: 90, hp: 90, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Pikachu', rarity: 0, image: 'images/raichu.png' },
  { id: null, number: 27, name: 'Sandshrew', type: 'ground', maxhp: 50, hp: 50, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 8, image: 'images/sandshrew.png' },
  { id: null, number: 28, name: 'Sandslash', type: 'ground', maxhp: 75, hp: 75, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Sandshrew', rarity: 0, image: 'images/sandslash.png' },
  { id: null, number: 29, name: 'Nidoran♀', type: 'poison', maxhp: 45, hp: 45, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 8, image: 'images/nidoran.png' },
  { id: null, number: 30, name: 'Nidorina', type: 'poison', maxhp: 70, hp: 70, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Nidoran♀', rarity: 0, image: 'images/nidorina.png' },
  { id: null, number: 31, name: 'Nidoqueen', type: 'poison', maxhp: 90, hp: 90, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Nidorina', rarity: 0, image: 'images/nidoqueen.png' },
  { id: null, number: 32, name: 'Nidoran♂', type: 'poison', maxhp: 45, hp: 45, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 8, image: 'images/nidoran-m.png' },
  { id: null, number: 33, name: 'Nidorino', type: 'poison', maxhp: 70, hp: 70, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Nidoran♂', rarity: 0, image: 'images/nidorino.png' },
  { id: null, number: 34, name: 'Nidoking', type: 'poison', maxhp: 90, hp: 90, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Nidorino', rarity: 0, image: 'images/nidoking.png' },
  { id: null, number: 35, name: 'Clefairy', type: 'fairy', maxhp: 60, hp: 60, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 5, image: 'images/clefairy.png' },
  { id: null, number: 36, name: 'Clefable', type: 'fairy', maxhp: 90, hp: 90, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Clefairy', rarity: 0, image: 'images/clefable.png' },
  { id: null, number: 37, name: 'Vulpix', type: 'fire', maxhp: 35, hp: 35, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 7, image: 'images/vulpix.png' },
  { id: null, number: 38, name: 'Ninetales', type: 'fire', maxhp: 80, hp: 80, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Vulpix', rarity: 0, image: 'images/ninetales.png' },
  { id: null, number: 39, name: 'Jigglypuff', type: 'normal', maxhp: 40, hp: 40, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 7, image: 'images/jigglypuff.png' },
  { id: null, number: 40, name: 'Wigglytuff', type: 'normal', maxhp: 80, hp: 80, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Jigglypuff', rarity: 0, image: 'images/wigglytuff.png' },
  { id: null, number: 41, name: 'Zubat', type: 'poison', maxhp: 40, hp: 40, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 7, image: 'images/zubat.png' },
  { id: null, number: 42, name: 'Golbat', type: 'poison', maxhp: 75, hp: 75, maxxp: 20, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Zubat', rarity: 0, image: 'images/golbat.png' },
  { id: null, number: 43, name: 'Oddish', type: 'grass', maxhp: 45, hp: 45, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 8, image: 'images/oddish.png' },
  { id: null, number: 44, name: 'Gloom', type: 'grass', maxhp: 60, hp: 60, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Oddish', rarity: 0, image: 'images/gloom.png' },
  { id: null, number: 45, name: 'Vileplume', type: 'grass', maxhp: 90, hp: 90, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Gloom', rarity: 0, image: 'images/vileplume.png' },
  { id: null, number: 46, name: 'Paras', type: 'bug', maxhp: 35, hp: 35, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 7, image: 'images/paras.png' },
  { id: null, number: 47, name: 'Parasect', type: 'bug', maxhp: 70, hp: 70, maxxp: 20, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Paras', rarity: 0, image: 'images/parasect.png' },
  { id: null, number: 48, name: 'Venonat', type: 'bug', maxhp: 40, hp: 40, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 7, image: 'images/venonat.png' },
  { id: null, number: 49, name: 'Venomoth', type: 'bug', maxhp: 80, hp: 80, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Venonat', rarity: 0, image: 'images/venomoth.png' },
  { id: null, number: 50, name: 'Diglett', type: 'ground', maxhp: 35, hp: 35, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/diglett.png' },
  { id: null, number: 51, name: 'Dugtrio', type: 'ground', maxhp: 75, hp: 75, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Diglett', rarity: 0, image: 'images/dugtrio.png' },
  { id: null, number: 52, name: 'Meowth', type: 'normal', maxhp: 40, hp: 40, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/meowth.png' },
  { id: null, number: 53, name: 'Persian', type: 'normal', maxhp: 75, hp: 75, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Meowth', rarity: 0, image: 'images/persian.png' },
  { id: null, number: 54, name: 'Psyduck', type: 'water', maxhp: 50, hp: 50, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/psyduck.png' },
  { id: null, number: 55, name: 'Golduck', type: 'water', maxhp: 80, hp: 80, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Psyduck', rarity: 0, image: 'images/golduck.png' },
  { id: null, number: 56, name: 'Mankey', type: 'fighting', maxhp: 40, hp: 40, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/mankey.png' },
  { id: null, number: 57, name: 'Primeape', type: 'fighting', maxhp: 65, hp: 65, maxxp: 20, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Mankey', rarity: 0, image: 'images/primeape.png' },
  { id: null, number: 58, name: 'Growlithe', type: 'fire', maxhp: 55, hp: 55, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 5, image: 'images/growlithe.png' },
  { id: null, number: 59, name: 'Arcanine', type: 'fire', maxhp: 90, hp: 90, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Growlithe', rarity: 0, image: 'images/arcanine.png' },
  { id: null, number: 60, name: 'Poliwag', type: 'water', maxhp: 35, hp: 35, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/poliwag.png' },
  { id: null, number: 61, name: 'Poliwhirl', type: 'water', maxhp: 65, hp: 65, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Poliwag', rarity: 0, image: 'images/poliwhirl.png' },
  { id: null, number: 62, name: 'Poliwrath', type: 'water', maxhp: 90, hp: 90, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Poliwhirl', rarity: 0, image: 'images/poliwrath.png' },
  { id: null, number: 63, name: 'Abra', type: 'psychic', maxhp: 25, hp: 25, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 5, image: 'images/abra.png' },
  { id: null, number: 64, name: 'Kadabra', type: 'psychic', maxhp: 50, hp: 50, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Abra', rarity: 0, image: 'images/kadabra.png' },
  { id: null, number: 65, name: 'Alakazam', type: 'psychic', maxhp: 95, hp: 95, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Kadabra', rarity: 0, image: 'images/alakazam.png' },
  { id: null, number: 66, name: 'Machop', type: 'fighting', maxhp: 40, hp: 40, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 7, image: 'images/machop.png' },
  { id: null, number: 67, name: 'Machoke', type: 'fighting', maxhp: 60, hp: 60, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Machop', rarity: 0, image: 'images/machoke.png' },
  { id: null, number: 68, name: 'Machamp', type: 'fighting', maxhp: 95, hp: 95, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Machoke', rarity: 0, image: 'images/machamp.png' },
  { id: null, number: 69, name: 'Bellsprout', type: 'grass', maxhp: 30, hp: 30, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 7, image: 'images/bellsprout.png' },
  { id: null, number: 70, name: 'Weepinbell', type: 'grass', maxhp: 65, hp: 65, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Bellsprout', rarity: 0, image: 'images/weepinbell.png' },
  { id: null, number: 71, name: 'Victreebel', type: 'grass', maxhp: 85, hp: 85, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Weepinbell', rarity: 0, image: 'images/victreebel.png' },
  { id: null, number: 72, name: 'Tentacool', type: 'water', maxhp: 40, hp: 40, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/tentacool.png' },
  { id: null, number: 73, name: 'Tentacruel', type: 'water', maxhp: 80, hp: 80, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Tentacool', rarity: 0, image: 'images/tentacruel.png' },
  { id: null, number: 74, name: 'Geodude', type: 'rock', maxhp: 40, hp: 40, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 7, image: 'images/geodude.png' },
  { id: null, number: 75, name: 'Graveler', type: 'rock', maxhp: 55, hp: 55, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Geodude', rarity: 0, image: 'images/graveler.png' },
  { id: null, number: 76, name: 'Golem', type: 'rock', maxhp: 85, hp: 85, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Graveler', rarity: 0, image: 'images/golem.png' },
  { id: null, number: 77, name: 'Ponyta', type: 'fire', maxhp: 50, hp: 50, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/ponyta.png' },
  { id: null, number: 78, name: 'Rapidash', type: 'fire', maxhp: 80, hp: 80, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Ponyta', rarity: 0, image: 'images/rapidash.png' },
  { id: null, number: 79, name: 'Slowpoke', type: 'water', maxhp: 40, hp: 40, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 5, image: 'images/slowpoke.png' },
  { id: null, number: 80, name: 'Slowbro', type: 'water', maxhp: 85, hp: 85, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Slowpoke', rarity: 0, image: 'images/slowbro.png' },
  { id: null, number: 81, name: 'Magnemite', type: 'electric', maxhp: 35, hp: 35, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/magnemite.png' },
  { id: null, number: 82, name: 'Magneton', type: 'electric', maxhp: 80, hp: 80, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Magnemite', rarity: 0, image: 'images/magneton.png' },
  { id: null, number: 83, name: "Farfetch'd", type: 'normal', maxhp: 70, hp: 70, maxxp: 20, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 4, image: 'images/farfetchd.png' },
  { id: null, number: 84, name: 'Doduo', type: 'normal', maxhp: 35, hp: 35, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/doduo.png' },
  { id: null, number: 85, name: 'Dodrio', type: 'normal', maxhp: 70, hp: 70, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Doduo', rarity: 0, image: 'images/dodrio.png' },
  { id: null, number: 86, name: 'Seel', type: 'water', maxhp: 45, hp: 45, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/seel.png' },
  { id: null, number: 87, name: 'Dewgong', type: 'water', maxhp: 90, hp: 90, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Seel', rarity: 0, image: 'images/dewgong.png' },
  { id: null, number: 88, name: 'Grimer', type: 'poison', maxhp: 45, hp: 45, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 5, image: 'images/grimer.png' },
  { id: null, number: 89, name: 'Muk', type: 'poison', maxhp: 90, hp: 90, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Grimer', rarity: 0, image: 'images/muk.png' },
  { id: null, number: 90, name: 'Shellder', type: 'water', maxhp: 30, hp: 30, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 5, image: 'images/shellder.png' },
  { id: null, number: 91, name: 'Cloyster', type: 'water', maxhp: 80, hp: 80, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Shellder', rarity: 0, image: 'images/cloyster.png' },
  { id: null, number: 92, name: 'Gastly', type: 'ghost', maxhp: 30, hp: 30, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/gastly.png' },
  { id: null, number: 93, name: 'Haunter', type: 'ghost', maxhp: 55, hp: 55, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Gastly', rarity: 0, image: 'images/haunter.png' },
  { id: null, number: 94, name: 'Gengar', type: 'ghost', maxhp: 75, hp: 75, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Haunter', rarity: 0, image: 'images/gengar.png' },
  { id: null, number: 95, name: 'Onix', type: 'rock', maxhp: 80, hp: 80, maxxp: 40, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 5, image: 'images/onix.png' },
  { id: null, number: 96, name: 'Drowzee', type: 'psychic', maxhp: 60, hp: 60, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 5, image: 'images/drowzee.png' },
  { id: null, number: 97, name: 'Hypno', type: 'psychic', maxhp: 85, hp: 85, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Drowzee', rarity: 0, image: 'images/hypno.png' },
  { id: null, number: 98, name: 'Krabby', type: 'water', maxhp: 40, hp: 40, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/krabby.png' },
  { id: null, number: 99, name: 'Kingler', type: 'water', maxhp: 75, hp: 75, maxxp: 20, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Krabby', rarity: 0, image: 'images/kingler.png' },
  { id: null, number: 100, name: 'Voltorb', type: 'electric', maxhp: 40, hp: 40, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 7, image: 'images/voltorb.png' },
  { id: null, number: 101, name: 'Electrode', type: 'electric', maxhp: 80, hp: 80, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Voltorb', rarity: 0, image: 'images/electrode.png' },
  { id: null, number: 102, name: 'Exeggcute', type: 'grass', maxhp: 60, hp: 60, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/exeggcute.png' },
  { id: null, number: 103, name: 'Exeggutor', type: 'grass', maxhp: 95, hp: 95, maxxp: 40, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Exeggcute', rarity: 0, image: 'images/exeggutor.png' },
  { id: null, number: 104, name: 'Cubone', type: 'ground', maxhp: 50, hp: 50, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/cubone.png' },
  { id: null, number: 105, name: 'Marowak', type: 'ground', maxhp: 80, hp: 80, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Cubone', rarity: 0, image: 'images/marowak.png' },
  { id: null, number: 106, name: 'Hitmonlee', type: 'fighting', maxhp: 80, hp: 80, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 2, image: 'images/hitmonlee.png' },
  { id: null, number: 107, name: 'Hitmonchan', type: 'fighting', maxhp: 80, hp: 80, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 2, image: 'images/hitmonchan.png' },
  { id: null, number: 108, name: 'Lickitung', type: 'normal', maxhp: 75, hp: 75, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 5, image: 'images/lickitung.png' },
  { id: null, number: 109, name: 'Koffing', type: 'poison', maxhp: 40, hp: 40, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 7, image: 'images/koffing.png' },
  { id: null, number: 110, name: 'Weezing', type: 'poison', maxhp: 70, hp: 70, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Weezing', rarity: 0, image: 'images/weezing.png' },
  { id: null, number: 111, name: 'Rhyhorn', type: 'ground', maxhp: 80, hp: 80, maxxp: 30, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 6, image: 'images/rhyhorn.png' },
  { id: null, number: 112, name: 'Rhydon', type: 'ground', maxhp: 100, hp: 100, maxxp: 50, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Rhyhorn', rarity: 0, image: 'images/rhydon.png' },
  { id: null, number: 113, name: 'Chansey', type: 'normal', maxhp: 90, hp: 90, maxxp: 40, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 2, image: 'images/chansey.png' },
  { id: null, number: 114, name: 'Tangela', type: 'grass', maxhp: 75, hp: 75, maxxp: 20, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 6, image: 'images/tangela.png' },
  { id: null, number: 115, name: 'Kangaskhan', type: 'normal', maxhp: 100, hp: 100, maxxp: 50, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 3, image: 'images/kangaskhan.png' },
  { id: null, number: 116, name: 'Horsea', type: 'water', maxhp: 30, hp: 30, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 7, image: 'images/horsea.png' },
  { id: null, number: 117, name: 'Seadra', type: 'water', maxhp: 65, hp: 65, maxxp: 20, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Horsea', rarity: 0, image: 'images/seadra.png' },
  { id: null, number: 118, name: 'Goldeen', type: 'water', maxhp: 45, hp: 45, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 7, image: 'images/goldeen.png' },
  { id: null, number: 119, name: 'Seaking', type: 'water', maxhp: 80, hp: 80, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Goldeen', rarity: 0, image: 'images/seaking.png' },
  { id: null, number: 120, name: 'Staryu', type: 'water', maxhp: 30, hp: 30, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 7, image: 'images/staryu.png' },
  { id: null, number: 121, name: 'Starmie', type: 'water', maxhp: 80, hp: 80, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Staryu', rarity: 0, image: 'images/starmie.png' },
  { id: null, number: 122, name: 'Mr. Mime', type: 'psychic', maxhp: 70, hp: 70, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 5, image: 'images/mr-mime.png' },
  { id: null, number: 123, name: 'Scyther', type: 'bug', maxhp: 70, hp: 70, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 4, image: 'images/scyther.png' },
  { id: null, number: 124, name: 'Jynx', type: 'ice', maxhp: 65, hp: 65, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 5, image: 'images/jynx.png' },
  { id: null, number: 125, name: 'Electabuzz', type: 'electric', maxhp: 65, hp: 65, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 5, image: 'images/electabuzz.png' },
  { id: null, number: 126, name: 'Magmar', type: 'fire', maxhp: 65, hp: 65, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 5, image: 'images/magmar.png' },
  { id: null, number: 127, name: 'Pinsir', type: 'bug', maxhp: 65, hp: 65, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 5, image: 'images/pinsir.png' },
  { id: null, number: 128, name: 'Tauros', type: 'normal', maxhp: 75, hp: 75, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 4, image: 'images/tauros.png' },
  { id: null, number: 129, name: 'Magikarp', type: 'water', maxhp: 20, hp: 20, maxxp: 15, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 8, image: 'images/magikarp.png' },
  { id: null, number: 130, name: 'Gyarados', type: 'water', maxhp: 95, hp: 95, maxxp: 40, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Magikarp', rarity: 0, image: 'images/gyarados.png' },
  { id: null, number: 131, name: 'Lapras', type: 'water', maxhp: 95, hp: 95, maxxp: 45, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 3, image: 'images/lapras.png' },
  { id: null, number: 132, name: 'Ditto', type: 'normal', maxhp: 50, hp: 50, maxxp: 10, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 4, image: 'images/ditto.png' },
  { id: null, number: 133, name: 'Eevee', type: 'normal', maxhp: 45, hp: 45, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 4, image: 'images/eevee.png' },
  { id: null, number: 134, name: 'Vaporeon', type: 'water', maxhp: 70, hp: 70, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Eevee', rarity: 0, image: 'images/vaporeon.png' },
  { id: null, number: 135, name: 'Jolteon', type: 'electric', maxhp: 70, hp: 70, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Eevee', rarity: 0, image: 'images/jolteon.png' },
  { id: null, number: 136, name: 'Flareon', type: 'fire', maxhp: 70, hp: 70, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Eevee', rarity: 0, image: 'images/flareon.png' },
  { id: null, number: 137, name: 'Porygon', type: 'normal', maxhp: 70, hp: 70, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 4, image: 'images/porygon.png' },
  { id: null, number: 138, name: 'Omanyte', type: 'rock', maxhp: 35, hp: 35, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 2, image: 'images/omanyte.png' },
  { id: null, number: 139, name: 'Omastar', type: 'rock', maxhp: 70, hp: 70, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Omanyte', rarity: 0, image: 'images/omastar.png' },
  { id: null, number: 140, name: 'Kabuto', type: 'rock', maxhp: 30, hp: 30, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 2, image: 'images/kabuto.png' },
  { id: null, number: 141, name: 'Kabutops', type: 'rock', maxhp: 70, hp: 70, maxxp: 25, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Kabuto', rarity: 0, image: 'images/kabutops.png' },
  { id: null, number: 142, name: 'Aerodactyl', type: 'rock', maxhp: 80, hp: 80, maxxp: 40, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 1, image: 'images/aerodactyl.png' },
  { id: null, number: 143, name: 'Snorlax', type: 'normal', maxhp: 80, hp: 80, maxxp: 40, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 2, image: 'images/snorlax.png' },
  { id: null, number: 144, name: 'Articuno', type: 'ice', maxhp: 90, hp: 90, maxxp: 45, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 1, image: 'images/articuno.png' },
  { id: null, number: 145, name: 'Zapdos', type: 'electric', maxhp: 90, hp: 90, maxxp: 45, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 1, image: 'images/zapdos.png' },
  { id: null, number: 146, name: 'Moltres', type: 'fire', maxhp: 90, hp: 90, maxxp: 45, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 1, image: 'images/moltres.png' },
  { id: null, number: 147, name: 'Dratini', type: 'dragon', maxhp: 40, hp: 40, maxxp: 10, xp: 0, starter: false, canEvolve: true, evolvesFrom: null, rarity: 4, image: 'images/dratini.png' },
  { id: null, number: 148, name: 'Dragonair', type: 'dragon', maxhp: 60, hp: 60, maxxp: 20, xp: 0, starter: false, canEvolve: true, evolvesFrom: 'Dratini', rarity: 3, image: 'images/dragonair.png' },
  { id: null, number: 149, name: 'Dragonite', type: 'dragon', maxhp: 90, hp: 90, maxxp: 30, xp: 0, starter: false, canEvolve: false, evolvesFrom: 'Dragonair', rarity: 0, image: 'images/dragonite.png' },
  { id: null, number: 150, name: 'Mewtwo', type: 'special', maxhp: 100, hp: 100, maxxp: 50, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 1, image: 'images/mewtwo.png' },
  { id: null, number: 151, name: 'Mew', type: 'special', maxhp: 100, hp: 100, maxxp: 50, xp: 0, starter: false, canEvolve: false, evolvesFrom: null, rarity: 1, image: 'images/mew.png' },
];

const leaders = [
  {
    name: "Brock",
    location: "pewterCity",
    image: 'images/brock.png',
    intro: "I'm Brock! I'm Pewter's Gym Leader! I believe in rock hard defense and determination! That's why my Pokémon are all the Rock-type! Do you still want to challenge me? Fine then! Show me your best!",
    loss: "I took you for granted. As proof of your victory, here's the Boulder Badge!",
    party: [
      { number: 74, name: 'Geodude', type: 'rock', hp: 40, maxhp: 40, image: 'images/geodude.png' },
      { number: 95, name: 'Onix', type: 'rock', hp: 80, maxhp: 80, image: 'images/onix.png' }
    ]
  },
  {
    name: "Misty",
    location: "ceruleanCity",
    image: 'images/misty.png',
    intro: "Hi, you're a new face! Trainers who want to turn pro have to have a policy about Pokémon! What is your approach when you catch Pokémon? My policy is an all-out offensive with Water-type Pokémon!",
    loss: "Wow! You're too much! All right! You can have the Cascade Badge to show you beat me!",
    party: [
      { number: 120, name: 'Staryu', type: 'water', hp: 30, maxhp: 30, image: 'images/staryu.png' },
      { number: 121, name: 'Starmie', type: 'water', hp: 80, maxhp: 80, image: 'images/starmie.png' }
    ]
  },
  {
    name: "Lt. Surge",
    location: "vermilionCity",
    image: 'images/ltsurge.png',
    intro: "Ten-hut! Welcome to Vermilion Gym! Will you look at that, a pint-size challenger! Hahaha! You've got big and brassy nerves to take me on with your puny power! A Pokémon battle is war! I'll show you, civilian! I'll shock you into surrender!",
    loss: "Whoa! You're the real deal, kid! Fine then, take the Thunder Badge!",
    party: [
      { number: 100, name: 'Voltorb', type: 'electric', hp: 40, maxhp: 40, image: 'images/voltorb.png' },
      { number: 25, name: 'Pikachu', type: 'electric', hp: 45, maxhp: 45, image: 'images/pikachu.png' },
      { number: 26, name: 'Raichu', type: 'electric', hp: 90, maxhp: 90, image: 'images/raichu.png' }
    ]
  },
  {
    name: "Erika",
    location: "celadonCity",
    image: 'images/erika.png',
    intro: "Hello. Lovely weather isn't it? It's so pleasant. ...Oh dear... I must have dozed off. Welcome. My name is Erika. I am the Leader of Celadon Gym. I teach the art of flower arranging. My Pokémon are of the grass-type. Oh, I'm sorry, I had no idea that you wished to challenge me. Very well, but I shall not lose.",
    loss: "Oh! I concede defeat. You are remarkably strong. I must confer you the Rainbow Badge.",
    party: [
      { number: 71, name: 'Victreebel', type: 'grass', hp: 80, maxhp: 80, image: 'images/victreebel.png' },
      { number: 45, name: 'Vileplume', type: 'grass', hp: 90, maxhp: 90, image: 'images/vileplume.png' },
      { number: 114, name: 'Tangela', type: 'grass', hp: 75, maxhp: 75, image: 'images/tangela.png' }
    ]
  },
  {
    name: "Koga",
    location: "fuchsiaCity",
    image: 'images/koga.png',
    intro: "Fwahahaha! A mere trainer like you dares to challenge me? Very well, I shall show you true terror as a ninja master! You shall feel the despair of poison and sleep techniques!",
    loss: "Humph! You have proven your worth! Here! Take the Soul Badge!",
    party: [
      { number: 109, name: 'Koffing', type: 'poison', hp: 40, maxhp: 40, image: 'images/koffing.png' },
      { number: 109, name: 'Koffing', type: 'poison', hp: 50, maxhp: 50, image: 'images/koffing.png' },
      { number: 89, name: 'Muk', type: 'poison', hp: 90, maxhp: 90, image: 'images/muk.png' },
      { number: 110, name: 'Weezing', type: 'poison', hp: 70, maxhp: 70, image: 'images/weezing.png' }
    ]
  },
  {
    name: "Sabrina",
    location: "saffronCity",
    image: 'images/sabrina.png',
    intro: "I had a vision of your arrival! I have had psychic powers since I was a child. I first learned to bend spoons with my mind. I dislike fighting, but if you wish, I will show you my powers!",
    loss: "I'm shocked! But, a loss is a loss. I admit I didn't work hard enough to win! You earned the Marsh Badge!",
    party: [
      { number: 64, name: 'Kadabra', type: 'psychic', hp: 50, maxhp: 50, image: 'images/kadabra.png' },
      { number: 122, name: 'Mr. Mime', type: 'psychic', hp: 70, maxhp: 70, image: 'images/mr-mime.png' },
      { number: 49, name: 'Venomoth', type: 'bug', hp: 80, maxhp: 80, image: 'images/venomoth.png' },
      { number: 65, name: 'Alakazam', type: 'psychic', hp: 95, maxhp: 95, image: 'images/alakazam.png' }
    ]
  },
  {
    name: "Blaine",
    location: "cinnabarIsland",
    image: 'images/blaine.png',
    intro: "Hah! I'm Blaine! I am the Leader of Cinnabar Gym! My fiery Pokémon will incinerate all challengers! Hah! You better have potions!",
    loss: "I've burnt out! You have earned the Volcano Badge!",
    party: [
      { number: 58, name: 'Growlithe', type: 'fire', hp: 65, maxhp: 65, image: 'images/growlithe.png' },
      { number: 77, name: 'Ponyta', type: 'fire', hp: 70, maxhp: 70, image: 'images/ponyta.png' },
      { number: 78, name: 'Rapidash', type: 'fire', hp: 95, maxhp: 95, image: 'images/rapidash.png' },
      { number: 59, name: 'Arcanine', type: 'fire', hp: 110, maxhp: 110, image: 'images/arcanine.png' }
    ]
  },
  {
    name: "Giovanni",
    location: "viridianCity",
    image: 'images/giovanni.png',
    intro: "So! I must say, I am impressed you got here!",
    loss: "WHAT! This cannot be!",
    party: [
      { number: 111, name: 'Rhyhorn', type: 'ground', hp: 80, maxhp: 80, image: 'images/rhyhorn.png' },
      { number: 51, name: 'Dugtrio', type: 'ground', hp: 75, maxhp: 75, image: 'images/dugtrio.png' },
      { number: 31, name: 'Nidoqueen', type: 'poison', hp: 90, maxhp: 90, image: 'images/nidoqueen.png' },
      { number: 34, name: 'Nidoking', type: 'poison', hp: 90, maxhp: 90, image: 'images/nidoking.png' },
      { number: 112, name: 'Rhydon', type: 'ground', hp: 100, maxhp: 100, image: 'images/rhydon.png' }
    ]
  }
];

const eliteFour = [
  {
    name: "Lorelei",
    image: 'images/lorelei.png',
    intro: "Welcome to Pokémon League! I am Lorelei of the Elite Four! No one can best me when it comes to icy Pokémon! Freezing moves are powerful! Your Pokémon will be at my mercy when they are frozen solid! Hahaha! Are you ready?",
    loss: "You're better than I thought! Go on ahead! You only got a taste of Pokémon League power!",
    party: [
      { number: 87, name: 'Dewgong', type: 'water', hp: 120, maxhp: 120, image: 'images/dewgong.png' },
      { number: 91, name: 'Cloyster', type: 'water', hp: 110, maxhp: 110, image: 'images/cloyster.png' },
      { number: 80, name: 'Slowbro', type: 'water', hp: 105, maxhp: 105, image: 'images/slowbro.png' },
      { number: 124, name: 'Jynx', type: 'ice', hp: 95, maxhp: 95, image: 'images/jynx.png' },
      { number: 131, name: 'Lapras', type: 'water', hp: 125, maxhp: 125, image: 'images/lapras.png' }
    ]
  },
  {
    name: "Bruno",
    image: 'images/bruno.png',
    intro: "I am Bruno of the Elite Four! Through rigorous training, people and Pokémon can become stronger! I've weight trained with my Pokémon! And that will never change! We will grind you down with our superior power! Hoo hah!",
    loss: "My job is done! Go face your next challenge!",
    party: [
      { number: 95, name: 'Onix', type: 'rock', hp: 110, maxhp: 110, image: 'images/onix.png' },
      { number: 107, name: 'Hitmonchan', type: 'fighting', hp: 110, maxhp: 110, image: 'images/hitmonchan.png' },
      { number: 106, name: 'Hitmonlee', type: 'fighting', hp: 110, maxhp: 110, image: 'images/hitmonlee.png' },
      { number: 95, name: 'Onix', type: 'rock', hp: 110, maxhp: 110, image: 'images/onix.png' },
      { number: 68, name: 'Machamp', type: 'fighting', hp: 120, maxhp: 120, image: 'images/machamp.png' }
    ]
  },
  {
    name: "Agatha",
    image: 'images/agatha.png',
    intro: "I am Agatha of the Elite Four! Oak's taken a lot of interest in you! That old duff was once tough and handsome! That was decades ago! Now he just wants to fiddle with his Pokédex! He's wrong! Pokémon are for fighting! I'll show you how a real trainer fights!",
    loss: "You win! I see what the old duff sees in you now. I've nothing else to say. Run along now, child!",
    party: [
      { number: 94, name: 'Gengar', type: 'ghost', hp: 105, maxhp: 105, image: 'images/gengar.png' },
      { number: 42, name: 'Golbat', type: 'poison', hp: 105, maxhp: 105, image: 'images/golbat.png' },
      { number: 93, name: 'Haunter', type: 'ghost', hp: 85, maxhp: 85, image: 'images/haunter.png' },
      { number: 24, name: 'Arbok', type: 'poison', hp: 90, maxhp: 90, image: 'images/arbok.png' },
      { number: 94, name: 'Gengar', type: 'ghost', hp: 105, maxhp: 105, image: 'images/gengar.png' }
    ]
  },
  {
    name: "Lance",
    image: 'images/lance.png',
    intro: "Ah! I heard about you! I lead the Elite Four! You can call me Lance the dragon trainer! You know that dragons are mythical Pokémon! They're hard to catch and raise, but their powers are superior! They're virtually indestructible! Well, are you ready to lose? Your League challenge ends with me!",
    loss: "I still can't believe my dragons lost to you! You're now the Pokémon League champion!",
    party: [
      { number: 130, name: 'Gyarados', type: 'water', hp: 125, maxhp: 125, image: 'images/gyarados.png' },
      { number: 148, name: 'Dragonair', type: 'dragon', hp: 90, maxhp: 90, image: 'images/dragonair.png' },
      { number: 148, name: 'Dragonair', type: 'dragon', hp: 90, maxhp: 90, image: 'images/dragonair.png' },
      { number: 142, name: 'Aerodactyl', type: 'rock', hp: 110, maxhp: 110, image: 'images/aerodactyl.png' },
      { number: 149, name: 'Dragonite', type: 'dragon', hp: 120, maxhp: 120, image: 'images/dragonite.png' }
    ]
  }
]

const characters = [
  { name: 'Leaf', image: 'images/leaf.png' },
  { name: 'Red', image: 'images/red.png' },
  { name: 'Elaine', image: 'images/elaine.png' },
  { name: 'Chase', image: 'images/chase.png' }
];

const trainerIntros = [
  "Have we met or not? I don’t really remember. Well, I guess it’s nice to meet you anyway!",
  "No need to waste time saying hello. Bring it on whenever you’re ready!",
  "I’ve raised my Pokémon with great care. You’re not allowed to hurt them!",
  "Let’s have a fun Pokémon battle!",
  "I’ll show you the ropes of how to really use Pokémon!",
  "A serious battle starts from a serious beginning! Are you sure you’re ready?",
  "You’re only young once. And you only get one shot at a given battle. Soon, you’ll be nothing but a memory.",
  "You’d better go easy on me, OK? Though I’ll be seriously fighting!",
  "Um, um, um, you know what? These Pokémon are my friends.",
  "I’m a beginner, but I’ll do my best! I’ll give it everything I can. Watch me!",
  "I’m gaining as much experience as I can because I want to be a Gym Leader someday.",
  "We’re about to battle, but that doesn’t mean we can’t be polite! Good luck!",
  "Hey! This is no laughing matter! We’re about to battle!",
  "Ah... You look strong... I hope I’ll be all right...",
  "Experience begets power! Isn’t that what they say?! Anyway, won’t you battle me?",
  "What kind of Pokémon do you like? Hey, come on, show me!",
  "Chosen Trainers will choose chosen Pokémon.",
  "Didn’t you come here for a Pokémon battle?",
  "Oh, do you want to see the Pokémon I am proudest of?",
  "Muwahaha! The legend of my invincibility begins with you!",
  "Wait! Wait! I’m still trying to think up my strategy!",
  "Huhuehuehue... No crying when you lose...",
  "Fair and square? Don’t make me laugh! There’s no point to battles if you don’t win!",
  "Br-bring it on! Bearing in mind that I’m a b-beginner!",
  "Wanna give me a hand with my training? It’s all for the sake of my future dreams!",
  "People say I’m a diamond in the rough. Sure you wanna battle with me?",
  "Are your preparations complete? I would like to ask you for a battle.",
  "My Pokémon will trump yours! You can bet on losing!",
  "I’ll show you we can break you. We’ve been training in the field!",
  "Oh, you look lively! What d’ya say we battle?",
  "You’d best not send out any weak Pokémon!",
  "If you don’t have great Pokémon, you’ll never have a great battle.",
  "My last ever battle... That’s the way I’d like us to view this match...",
  "I will evaluate your ability.",
  "Shall I give you a tip for training good Pokémon?"
];

const trainerLoss = [
  "No way... NO WAY! How could I lose again...",
  "No! I lost!",
  "Whoa! You are incredible! I’m amazed and surprised!",
  "I won’t lose next time! Let’s battle again sometime!",
  "That was close... I just barely lost...",
  "The Pokémon you use... Do you really like them?",
  "Ahhhhh! And I lost! This is not my day.",
  "Did you enjoy the battle with me?",
  "I am happy! Happy, I tell you! Don’t look at me like that!",
  "You’re actually good, aren’t you?"
];